- name: Add jenkins repository
  kubernetes.core.helm_repository:
    name: jenkins
    repo_url: "https://charts.jenkins.io"

- name: Install jenkins with existing credentials
  kubernetes.core.helm:
    name: jenkins
    chart_ref: jenkins/jenkins
    release_namespace: jenkins
    create_namespace: true
    values:
      controller:
        serviceType: NodePort
        nodePort: 32000
        existingSecret: jenkins-credentials
        createSecret: false
