apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  labels:
    app: notifier
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: notifier
          image: ghcr.io/itp24102/notifier:latest
          ports:
            - containerPort: 8080
