apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  labels:
    app: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: processor
          image: ghcr.io/itp24102/processor:latest
          ports:
            - containerPort: 8080
