pipeline {
  agent {
    kubernetes {
      yamlFile 'jenkins/k8s-agent.yaml'
    }
  }

  environment {
    FUNCTION_NAME = 'seismicity-function'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Prepare') {
      steps {
        dir('services/poller') {
          container('python') {
            sh '''
              rm -rf build function.zip
              mkdir -p build
              python -m ensurepip --upgrade
              pip install -r requirements.txt -t build/
              cp src/handler.py build/
            '''
          }
        }
      }
    }

    stage('Package') {
      steps {
        dir('services/poller/build') {
          container('python') {
            sh '''
              apt-get update && apt-get install -y zip
              zip -r ../function.zip .
            '''
          }
        }
      }
    }

    stage('Deploy to AWS Lambda') {
      steps {
        dir('services/poller') {
          withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials']]) {
            sh '''
              aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://function.zip \
              --region eu-west-1
            '''
          }
        }
      }
    }

    stage('Apply Infrastructure with OpenTofu') {
      steps {
        dir('infrastructure/opentofu/aws/handler') {
          sh '''
            tofu init
            tofu apply -auto-approve
          '''
        }
      }
    }
  }

  post {
    failure {
      echo "❌ Κάποιο στάδιο απέτυχε."
    }
    success {
      echo "✅ Όλα τα στάδια ολοκληρώθηκαν επιτυχώς."
    }
  }
}
