pipeline {
  agent any
  environment {
    REGISTRY = 'ghcr.io/itp24102'
    IMAGE = "${REGISTRY}/poller:latest"
  }
  stages {
    stage('Checkout') { steps { checkout scm } }
    stage('Build')    { sh "docker build -t ${IMAGE} services/poller" }
    stage('Push') {
      withCredentials([usernamePassword(credentialsId: 'ghcr-pat', 
                                       usernameVariable: 'USER', 
                                       passwordVariable: 'PAT')]) {
        sh "echo $PAT | docker login ghcr.io -u $USER --password-stdin"
        sh "docker push ${IMAGE}"
      }
    }
    stage('Notify') {
      // trigger ArgoCD to pick up new image via Git update
      sh "argocd app sync seismicity-app"
    }
  }
}
