- name: Install prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: prometheus
    create_namespace: true
    values:
      prometheus:
        service:
          type: NodePort
          nodePort: 32001