pipeline {
  agent {
    docker {
      image 'python:3.10'
      args '-u root'
    }
  }

  environment {
    FUNCTION_NAME = 'influx-writer'
  }

  stages {
    stage('Prepare') {
      steps {
        sh 'rm -rf build influx_writer.zip'
        sh 'mkdir -p build'
        sh 'pip install -r requirements.txt -t build/'
        sh 'cp influx_writer.py build/'
      }
    }

    stage('Package') {
      steps {
        dir('build') {
          sh 'zip -r ../influx_writer.zip .'
        }
      }
    }

    stage('Deploy to AWS') {
      steps {
        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials']]) {
          sh 'aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://influx_writer.zip'
        }
      }
    }
  }

  post {
    success {
      echo '✅ Lambda influx-writer deployed successfully.'
    }
    failure {
      echo '❌ Lambda influx-writer deploy failed.'
    }
  }
}
