pipeline {
  agent {
    kubernetes {
      yamlFile 'jenkins/k8s-agent.yaml'
    }
  }
  environment {
    FUNCTION_NAME = 'influx-writer'
  }
  options {
    skipDefaultCheckout()
  }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Prepare') {
      steps {
        dir('services/influx-writer') {
          container('python') {
            sh '''
              rm -rf build influx_writer.zip
              mkdir -p build
              python -m ensurepip --upgrade
              pip install -r requirements.txt -t build/
              cp src/influx_writer.py build/
            '''
          }
        }
      }
    }

    stage('Package') {
      steps {
        dir('services/influx-writer/build') {
          container('python') {
            sh 'zip -r ../influx_writer.zip .'
          }
        }
      }
    }

    stage('Deploy to AWS Lambda') {
      steps {
        dir('services/influx-writer') {
          withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials']]) {
            container('python') {
              sh 'aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://influx_writer.zip --region eu-west-1'
            }
          }
        }
      }
    }

    stage('Apply Infrastructure with OpenTofu') {
      steps {
        dir('infrastructure/opentofu/aws') {
          container('python') {
            sh 'tofu init && tofu apply -auto-approve'
          }
        }
      }
    }
  }

  post {
    failure {
      echo "❌ Κάποιο στάδιο απέτυχε."
    }
    success {
      echo "✅ Όλα τα στάδια ολοκληρώθηκαν επιτυχώς!"
    }
  }
}
