pipeline {
  agent {
    kubernetes {
      yamlFile 'jenkins/k8s-agent.yaml'
    }
  }

  environment {
    FUNCTION_NAME = 'influx-writer'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Prepare') {
      steps {
        dir('services/influx-writer') {
          container('python') {
            sh '''
              rm -rf build influx_writer.zip
              mkdir -p build
              python -m ensurepip --upgrade
              pip install -r requirements.txt -t build/
              cp src/influx_writer.py build/
            '''
          }
        }
      }
    }

    stage('Package') {
      steps {
        dir('services/influx-writer/build') {
          container('python') {
            sh 'apt-get update && apt-get install -y zip && zip -r ../influx_writer.zip .'
          }
        }
      }
    }

    stage('Deploy to AWS Lambda') {
      steps {
        dir('services/influx-writer') {
          container('python') {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials']]) {
              sh '''
                apt-get update && apt-get install -y unzip curl
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                ./aws/install
                aws --version
                aws lambda update-function-code \
                  --function-name $FUNCTION_NAME \
                  --zip-file fileb://influx_writer.zip \
                  --region eu-west-1
              '''
            }
          }
        }
      }
    }

    stage('Apply Infrastructure with OpenTofu') {
      steps {
        dir('infrastructure/opentofu/aws') {
          sh '''
            tofu init
            tofu apply -auto-approve
          '''
        }
      }
    }
  }

  post {
    success {
      echo "✅ Λειτουργία επιτυχής."
    }
    failure {
      echo "❌ Κάποιο στάδιο απέτυχε."
    }
  }
}
