apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: influx-writer
spec:
  containers:
    - name: python
      image: ghcr.io/itp24102/influx-writer-tofu
      command:
        - cat
      tty: true
    - name: awscli
      image: ghcr.io/itp24102/influx-writer-tofu
      command:
        - cat
      tty: true
    - name: jnlp
      image: jenkins/inbound-agent:3309.v27b_9314fd1a_4-1
      args: [""]
      env:
        - name: JENKINS_URL
          value: http://jenkins.jenkins.svc.cluster.local:8080/
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Never
