apiVersion: v1
kind: Pod
spec:
  containers:
    - name: python
      image: python:3.9-slim
      command:
        - cat
      tty: true
    - name: awscli
      image: amazon/aws-cli
      command:
        - cat
      tty: true
