apiVersion: v1
kind: Pod
metadata:
  labels:
    app: influx-writer
spec:
  containers:
    - name: python
      image: ghcr.io/itp24102/influx-writer-tofu
      command:
        - cat
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
    - name: awscli
      image: ghcr.io/itp24102/influx-writer-tofu
      command:
        - cat
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
  volumes:
    - name: workspace-volume
      emptyDir: {}
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux
