apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: influx-writer
spec:
  containers:
    - name: python
      image: python:3.9-slim
      command:
        - cat
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
    - name: awscli
      image: ghcr.io/itp24102/influx-writer-tofu
      command:
        - cat
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
    - name: jnlp
      image: jenkins/inbound-agent:3309.v27b_9314fd1a_4-1
      env:
        - name: JENKINS_URL
          value: http://jenkins.jenkins.svc.cluster.local:8080/
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
  volumes:
    - name: workspace-volume
      emptyDir: {}
