apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-agent
spec:
  containers:
    - name: python
      image: python:3.10-slim
      command:
        - cat
      tty: true
    - name: awscli
      image: amazon/aws-cli:2.15.30
      command:
        - cat
      tty: true
