apiVersion: v1
kind: Pod
spec:
containers:
    - name: python
      image: python:3.10-slim
      command:
      - cat
      tty: true
    - name: awscli
      image: ghcr.io/itp24102/seismicity/awscli-tofu:latest
      command:
      - cat
      tty: true
    - name: jnlp
      image: jenkins/inbound-agent:3309.v27b_9314fd1a_4-1
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      env:
        - name: JENKINS_URL
          value: http://jenkins.jenkins.svc.cluster.local:8080/
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
