- name: Δημιουργία φακέλου για InfluxDB
  file:
    path: /opt/influxdb
    state: directory
    mode: '0755'

- name: Αντιγραφή docker-compose.yml για InfluxDB
  template:
    src: influxdb-compose.yml.j2
    dest: /opt/influxdb/docker-compose.yml

- name: Εκκίνηση InfluxDB με Docker Compose (v2)
  community.docker.docker_compose_v2:
    project_src: /opt/influxdb
    state: present

