apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
  labels:
    app: ingest
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ingest
  template:
    metadata:
      labels:
        app: ingest
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ingest
          image: ghcr.io/itp24102/ingest:latest
          ports:
            - containerPort: 8080
