apiVersion: apps/v1
kind: Deployment
metadata:
  name: poller
  labels:
    app: poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poller
  template:
    metadata:
      labels:
        app: poller
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: poller
          image: ghcr.io/itp24102/poller:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            - name: S3_BUCKET
              value: seismicity-app-bucket
            - name: AWS_REGION
              value: eu-west-1
            - name: POLL_INTERVAL
              value: "10"  # Polling interval in seconds
